### ISSUE TITLE
Load configurations file

### ISSUE THREAD

**Issue by prophecy** [prophecy/SignAnImage#1]
This file should specify { dName, dPosition, ePosition, eTel }.
JSON format may be the easiest way. @teera123 Please help!!!!!

**Comment by prophecy** [comment]
Show image from file:
Maybe,,, can run the same scripts as this page (Image preview)
Reference: http://jsfiddle.net/LvsYc/

**Comment by teera123** [comment]
using image form is a nice idea. I think I will use this concept for all signature form.

**Comment by prophecy** [comment]
I implemented config.js, and make the page load configuration value when it's loaded.
form-inline still be supported.
